### PR TITLE
Use the same DataFrame in the filter that is being filtered

### PR DESCRIPTION
**Pull request by bryanculbertson**
This is an completely untested proposed fix for https://github.com/kuanb/peartree/issues/165

### CODE REVIEW

**Comment by kuanb** [comment]
Ergh I think test error is result of the version of OSMnx I use being way out of date.

**Comment by kuanb** [comment]
@bryanculbertson if you rebase master you should be able to retrigger test and it should pass - thanks!

**Comment by bryanculbertson** [comment]
@kuanb rebased and tests pass!

**Comment by kuanb** [comment]
Thanks, I'll cut a new release!

**Pull request merged**
